### ISSUE TITLE
template lorem ipsum

### ISSUE THREAD

**Issue by Dinesh101041** [nisarhassan12/portfolio-template#8]
change The description in your work and about section- there is dummt content lorem ipsum

**Comment by nisarhassan12** [comment]
Thanks, @Dinesh101041. It's just a template which anyone could use i.e it's not my real portfolio so updating the text is not that important. But If you like you can make a PR for sure.

**Comment by Dinesh101041** [comment]
okay bro its your  choice bro to make the pr  bro otherwise no problem bro

**Comment by nisarhassan12** [comment]
Ok. Thanks.
